//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InterioirDesignDBEntities : DbContext
    {
        public InterioirDesignDBEntities()
            : base("name=InterioirDesignDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<MainPicture> MainPicture { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
