//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Picture = new HashSet<Picture>();
        }
    
        public int ProjectId { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SortId { get; set; }
        public string Description { get; set; }
        public System.DateTime UploadTime { get; set; }
        public bool Display { get; set; }
        public string tmp1 { get; set; }
        public string tmp2 { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Picture { get; set; }
    }
}
